theme: jekyll-theme-tactile
title: Welcome to pdxiv’s homepage!
description: Feel free to bookmark this to keep an eye on my project updates
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://asdjalkdjalwjdqwokjp.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://asdjalkdjalwjdqwokjp.com"